### ISSUE TITLE
App crashes when player dies

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/MonoGameJam#301]
When the player character dies, following their removal from the visible play area, the app crashes with an "Index out of range" error.

I'm using this version (latest at the moment):
https://github.com/EnigmaDragons/MonoGameJam/commit/112a22e344c7d766b85e58c8c683b619fdb59edc

![image.png](https://zube.io/files/enigmadragons/ca819abf3da5b6ad0b4a2db0886e1598-image.png)

**Comment by gordykeene** [comment]
This may be intermittent, of the test case may not be fully accurate. Out of 4 tests, it occurred 3 times.

**Comment by fdrobidoux** [comment]
Yup, the death system I added doesn't seem to be working as intended. All it does now, is remove the character from the list of characters in GameWorld.

**Comment by SilasReinagel** [comment]
I think the problem is that CharacterTurns isn't aware of the death.
