### ISSUE TITLE
`ArgumentOutOfRangeException` happening again on enemy death.

### ISSUE THREAD

**Issue by fdrobidoux** [EnigmaDragons/MonoGameJam#341]
![image.png](https://zube.io/files/enigmadragons/b5d672173275be59990ea07b01441d33-image.png)
![image.png](https://zube.io/files/enigmadragons/19a3553d25157cfb7fa0aeff5b7ecfad-image.png)

**Comment by gordykeene** [comment]
I *think* I've been able to track this down to `CharacterTurns` line 16:
```cs
        public Character CurrentCharacter => Characters[_activeCharacterIndex];
```
Where, for some reason, `Characters.Count` is 0, even though there is at least one character still alive.

**Comment by SilasReinagel** [comment]
That does seem to be where the issue happens. It's likely due to a synchronization problem when an element is being removed from the list. 

Using a Concurrent collection of some sort, or locking write-access to the Index and the Collection should solve this issue.
