### ISSUE TITLE
Create Initial Main Menu Layout

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/MonoGameJam#39]

**Comment by fdrobidoux** [comment]
Would love to have a sketch-like idea of how the menu would look.
Just a layout, basically.

**Comment by SilasReinagel** [comment]
That's what the output of this ticket should be.

**Comment by SilasReinagel** [comment]
![image.png](https://zube.io/files/enigmadragons/b3d19b595dcc56f50bdab474eed9443d-image.png)
