### ISSUE TITLE
Available movement options and pathing disagree

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/MonoGameJam#528]
In the screenshot below, the mouse was placed over a tile that is rendered indicating it is an available moment option, however, the path will not allow selecting that tile. In the following turn, I was able to reach that tile, so I'm guessing the pathing is wrong.

![image.png](https://zube.io/files/enigmadragons/0f658dd70708876cec1b92d6272961ca-image.png)

**Comment by SilasReinagel** [comment]
Cannot replicate. Issue must have been resolved.
